ZayShop/Areas/Admin/Models/Slider/SliderCreateVM.cs
using System.ComponentModel.DataAnnotations;

namespace ZayShop.Areas.Admin.Models.Slider
{
    public class SliderCreateVM
    {
        [Required(ErrorMessage = "Tittle required")]
        [MinLength(3, ErrorMessage = "Tittle must contain at least 3 character")]
        [Display(Name = "Title")]
        public string Title { get; set; }
        [Required(ErrorMessage = "SubTittle required")]
        [MinLength(3, ErrorMessage = "SubTittle must contain at least 3 character")]
        [Display(Name = "SubTitle")]
        public string SubTitle { get; set; }
        [Required(ErrorMessage = "Description required")]
        [MinLength(3, ErrorMessage = "Description must contain at least 3 character")]
        [Display(Name = "Description")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Order required")]
        [Range(1,3, ErrorMessage = "Allowed order is 1-3")]
        [Display(Name = "Order")]
        public int Order { get; set; }
        [Required(ErrorMessage = "Image required")]
        [Display(Name = "Image")]
        public string Image { get; set; }


    }
}

ZayShop/Areas/Admin/Models/Slider/SliderDetailVM.cs
namespace ZayShop.Areas.Admin.Models.Slider
{
    public class SliderDetailVM
    {
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public int Order { get; set; }
        public string Image { get; set; }
    }
}

ZayShop/Areas/Admin/Models/Slider/SliderIndexVM.cs
namespace ZayShop.Areas.Admin.Models.Slider
{
    public class SliderIndexVM
    {
        public List<Entities.Slider> Sliders { get; set; }
    }
}

ZayShop/Areas/Admin/Models/Slider/SliderUpdateVM.cs
using System.ComponentModel.DataAnnotations;

namespace ZayShop.Areas.Admin.Models.Slider
{
    public class SliderUpdateVM
    {
        [Required(ErrorMessage = "Tittle required")]
        [MinLength(3, ErrorMessage = "Tittle must contain at least 3 character")]
        [Display(Name = "Title")]
        public string Title { get; set; }
        [Required(ErrorMessage = "SubTittle required")]
        [MinLength(3, ErrorMessage = "SubTittle must contain at least 3 character")]
        [Display(Name = "SubTitle")]
        public string SubTitle { get; set; }
        [Required(ErrorMessage = "Description required")]
        [MinLength(3, ErrorMessage = "Description must contain at least 3 character")]
        [Display(Name = "Description")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Order required")]
        [Range(1, 3, ErrorMessage = "Allowed order is 1-3")]
        [Display(Name = "Order")]
        public int Order { get; set; }
        [Required(ErrorMessage = "Image required")]
        [Display(Name = "Image")]
        public string Image { get; set; }


    }
}

ZayShop/Entities/Slider.cs
namespace ZayShop.Entities
{
    public class Slider : Base
    {
        public string Tittle { get; set; }
        public string SubTittle { get; set; }
        public string Description { get; set; }
        public string ImgSrc { get; set; }
        public int Order { get; set; }
    }
}

ZayShop/Models/Slider/SliderIndexVM.cs
namespace ZayShop.Models.Slider
{
    public class SliderIndexVM
    {
        public List<Entities.Slider> Sliders { get; set; }
    }
}

ZayShop/Areas/Admin/Controllers/SliderController.cs
using Microsoft.AspNetCore.Mvc;
using ZayShop.Areas.Admin.Models.Category;
using ZayShop.Areas.Admin.Models.Slider;
using ZayShop.Data;
using ZayShop.Entities;

namespace ZayShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderController : Controller
    {
        private readonly AppDbContext _context;
        public SliderController(AppDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var model = new SliderIndexVM
            {
                Sliders = _context.Sliders.ToList()
            };

            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(SliderCreateVM sliderModel)
        {
            if (!ModelState.IsValid) return View();
            if (_context.Sliders.Count() == 3)
            {
                ModelState.AddModelError("Image", "Limit of sliders is three delete one to add new");
            }
            var slider = _context.Sliders.FirstOrDefault(s => s.Tittle.ToLower() == sliderModel.Title.ToLower());
            if (slider != null)
            {
                ModelState.AddModelError("Tittle", "This tittle already used");
                return View();
            }
            slider = _context.Sliders.FirstOrDefault(s => s.Order == sliderModel.Order);
            if (slider != null)
            {
                ModelState.AddModelError("Order", "You have a slider which order is same");
                return View();
            }
            slider = new Slider
            {
                Tittle = sliderModel.Title,
                SubTittle = sliderModel.SubTitle,
                ImgSrc = sliderModel.Image,
                Description = sliderModel.Description,
                Order = sliderModel.Order,
                CreatedAt = DateTime.Now
            };
            _context.Sliders.Add(slider);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var slider = _context.Sliders.Find(id);
            if (slider == null) return NotFound();
            _context.Sliders.Remove(slider);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            var slider = _context.Sliders.Find(id);
            if (slider == null) return NotFound();
            var sliderModel = new SliderUpdateVM
            {
                Title = slider.Tittle,
                SubTitle = slider.SubTittle,
                Image = slider.ImgSrc,
                Description = slider.Description,
                Order = slider.Order
            };
            return View(sliderModel);
        }
        [HttpPost]
        public IActionResult Update(int id, SliderUpdateVM sliderModel)
        {
            if (!ModelState.IsValid) return View();
            var slider = _context.Sliders.Find(id);
            if (slider is null) return NotFound();
            var existSlider = _context.Sliders.Any(s => s.Tittle.ToLower() == sliderModel.Title.ToLower() && s.Id != id);
            if (existSlider)
            {
                ModelState.AddModelError("Tittle", "Tittle is already exists");
                return View();
            }
            existSlider = _context.Sliders.Any(s => s.Order == sliderModel.Order && s.Id != id);
            if (slider.Tittle != sliderModel.Title)
                slider.UpdatedAt = DateTime.Now;

            slider.Tittle = sliderModel.Title;
            slider.SubTittle = sliderModel.SubTitle;
            slider.Order = sliderModel.Order;
            slider.Description = sliderModel.Description;
            slider.ImgSrc = sliderModel.Image;

            _context.Sliders.Update(slider);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Detail(int id)
        {
            var slider = _context.Sliders.Find(id);
            if (slider is null) return NotFound();
            var model = new SliderDetailVM
            {
                Title = slider.Tittle,
                SubTitle = slider.SubTittle,
                Order = slider.Order,
                Description = slider.Description,
                Image = slider.ImgSrc
            };
            return View(model);
        }
    }
}

ZayShop/Areas/Admin/Views/Slider/Create.cshtml
@using ZayShop.Areas.Admin.Models.Slider
@model SliderCreateVM

<form method="post" asp-action="create" asp-controller="Slider">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" placeholder="Enter title" />
        <span asp-validation-for="Title" class="text-danger"></span>
        <br/>
        <label class="mt-3" asp-for="SubTitle"></label>
        <input asp-for="SubTitle" class="form-control" placeholder="Enter subtitle" />
        <span asp-validation-for="SubTitle" class="text-danger"></span>
        <br/>
        <label class="mt-3" asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control" placeholder="Enter description"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
        <br/>
        <label class="mt-3" asp-for="Order"></label>
        <input asp-for="Order" class="form-control" placeholder="Enter order" />
        <span asp-validation-for="Order" class="text-danger"></span>
        <br/>
        <label class="mt-3" asp-for="Image"></label>
        <input asp-for="Image" class="form-control" placeholder="Enter image address" />
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

ZayShop/Areas/Admin/Views/Slider/Detail.cshtml
@using ZayShop.Areas.Admin.Models.Slider
@model SliderDetailVM
<div id="template-mo-zay-hero-carousel" class="carousel slide" data-bs-ride="carousel">
    <ol class="carousel-indicators">
        <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="0" class="active"></li>
        <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="1"></li>
        <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">

        <div class="carousel-item active">
            <div class="container">
                <div class="row p-5">
                    <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                        <img class="img-fluid" src="@Model.Image" alt="">
                    </div>
                    <div class="col-lg-6 mb-0 d-flex align-items-center">
                        <div class="text-align-left align-self-center">
                            <h1 class="h1 text-success">@Model.Title</h1>
                            <h3 class="h2">@Model.SubTitle</h3>
                            <p>
                                @Model.Description
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ZayShop/Areas/Admin/Views/Slider/Index.cshtml
@using ZayShop.Areas.Admin.Models.Slider
@model SliderIndexVM

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Sliders</h1>
    <a class="btn btn-success" asp-action="create" asp-controller="Slider">Create</a>
</div>

<table class="table table-light">
    <thead>
        <tr>
            <th scope="col">Tittle</th>
            <th scope="col">SubTittle</th>
            <th scope="col">Image</th>
            <th scope="col">Order</th>
            <th scope="col">Created at</th>
            <th scope="col">Modified at</th>
            <th scope="col" class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var Slider in Model.Sliders.OrderBy(x => x.Order))
        {
            <tr>
                <td>@Slider.Tittle</td>
                <td>@Slider.SubTittle</td>
                <td><img width="100px" height="80px" src="@Slider.ImgSrc" alt="Alternate Text" /></td>
                <td>@Slider.Order</td>
                <td>@Slider.CreatedAt.ToString("dd/MM/yyyy HH:mm")</td>
                <td>@Slider.UpdatedAt?.ToString("dd/MM/yyyy HH:mm")</td>
                <td class="text-center d-flex justify-content-center">
                    <a class="btn btn-primary mx-2" asp-action="update" asp-controller="slider" asp-route-id="@Slider.Id">Update</a>
                    <form method="post" asp-action="delete" asp-controller="slider" asp-route-id="@Slider.Id">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                    <a class="btn btn-secondary mx-2" asp-action="detail" asp-controller="slider" asp-route-id="@Slider.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ZayShop/Areas/Admin/Views/Slider/Update.cshtml
@using ZayShop.Areas.Admin.Models.Slider
@model SliderUpdateVM

<form method="post" asp-action="update" asp-controller="Slider">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" placeholder="Enter title" />
        <span asp-validation-for="Title" class="text-danger"></span>
        <br />
        <label class="mt-3" asp-for="SubTitle"></label>
        <input asp-for="SubTitle" class="form-control" placeholder="Enter subtitle" />
        <span asp-validation-for="SubTitle" class="text-danger"></span>
        <br />
        <label class="mt-3" asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control" placeholder="Enter description"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
        <br />
        <label class="mt-3" asp-for="Order"></label>
        <input asp-for="Order" class="form-control" placeholder="Enter order" />
        <span asp-validation-for="Order" class="text-danger"></span>
        <br />
        <label class="mt-3" asp-for="Image"></label>
        <input asp-for="Image" class="form-control" placeholder="Enter image address" />
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</form>